import { createContext, useContext, useState, useCallback, useEffect, type ReactNode } from 'react';

type Lang = 'en' | 'ar';
type Theme = 'light' | 'dark';

interface LangContextValue {
  lang: Lang;
  toggleLang: () => void;
  t: (path: string, params?: Record<string, string>) => string;
  theme: Theme;
  setTheme: (t: Theme) => void;
  toggleTheme: () => void;
}

const LanguageContext = createContext<LangContextValue | null>(null);

const translations: Record<string, Record<string, unknown>> = {
  en: {
    nav: { home: "Home", plans: "Browse Plans", finder: "Plan Finder", help: "Help", speedTest: "Speed Test", profile: "Profile", signIn: "Sign In", game: "Game", chat: "Meet People" },
    hero: {
      headline: "Find your perfect plan in seconds",
      subheadline: "Compare 150+ plans from all Saudi carriers.",
      ctaFinder: "Find My Plan",
      ctaBrowse: "Browse All Plans",
      trust: "8 carriers \u2022 150+ plans",
    },
    howItWorks: {
      title: "How Simba Works",
      step1Title: "Tell us what you need",
      step1Desc: "Answer a few quick questions about your usage and budget.",
      step2Title: "We find the best matches",
      step2Desc: "Our smart engine scores every plan and picks the top options.",
      step3Title: "Buy directly from the carrier",
      step3Desc: "We redirect you to the official carrier site. No middlemen.",
    },
    finderCta: {
      title: "Not sure what you need?",
      subtitle: "Smart Advisor finds your perfect plan in 30 seconds",
      cta: "Start Smart Advisor",
    },
    trending: { title: "Trending Plans", seeAll: "See all plans" },
    deals: { title: "Active Deals", seeAll: "See all deals" },
    carriers: { title: "We compare plans from all licensed carriers" },
    whySimba: {
      title: "Why Simba?",
      card1Title: "We don't sell SIMs",
      card1Desc: "We redirect you to the carrier's official site. Zero risk, zero middlemen.",
      card2Title: "Unbiased recommendations",
      card2Desc: "We're not affiliated with any carrier. Our recommendations are 100% neutral.",
      card3Title: "Smart matching",
      card3Desc: "Our advisor analyzes your needs and finds the perfect plan from 150+ options.",
      card4Title: "Real support \u2014 always",
      card4Desc: "AI chat 24/7, live agents, WhatsApp, and phone. We're always here.",
    },
    stats: {
      plans: "Plans",
      carriers: "Carriers",
      free: "Free",
      support: "Support",
      freeLabel: "100%",
      supportLabel: "24/7",
    },
    footer: {
      tagline: "Find your perfect plan in seconds",
      disclaimer: "Simba is an independent comparison platform. Not affiliated with any carrier. All trademarks belong to their respective owners.",
      madeWith: "Made with \u2764 in Saudi Arabia",
      quickLinks: "Quick Links",
      company: "Company",
      aboutUs: "About Us",
    },
    planCard: {
      viewDetails: "View Details",
      compare: "Compare",
      selected: "Selected",
      perMonth: "/mo",
      sar: "SAR",
      data: "Data",
      mins: "Mins",
      sms: "SMS",
      unlimitedSocial: "Unlimited Social",
      social: "Social",
    },
    compareBar: {
      selected: "selected",
      of: "of",
      selectMore: "Select at least 2 plans",
      selectMoreShort: "Select more",
      compareNow: "Compare Now",
      compareAction: "Compare",
      maxToast: "You can compare up to 3 plans. Remove one to add another.",
    },
    chat: {
      greeting: "Hi! I'm Simba Bot. How can I help you today?",
      placeholder: "Type a message...",
    },
    browse: {
      title: "Browse All Plans",
      subtitle: "Compare 150+ plans from all Saudi carriers",
      searchPlaceholder: "Search plans...",
      allCarriers: "All Carriers",
      allTypes: "All Types",
      sortBy: "Sort by",
      sortBestValue: "Best Value",
      sortPriceLow: "Price: Low to High",
      sortPriceHigh: "Price: High to Low",
      sortDataHigh: "Data: Most First",
      sortDataLow: "Data: Least First",
      sortCallsHigh: "Calls: Most First",
      sortProvider: "Provider: A-Z",
      sortName: "Name: A-Z",
      sortNewest: "Newest First",
      showing: "Showing",
      plans: "plans",
      of: "of",
      noResults: "No plans match your filters",
      noResultsDesc: "Try adjusting your filters or search term",
      clearFilters: "Clear all filters",
      filters: "Filters",
      priceRange: "Price Range",
      dataRange: "Data",
      anyData: "Any",
      unlimited: "Unlimited",
      localCalls: "Local Calls",
      intlCalls: "International Calls",
      socialMedia: "Social Media Data",
      anyCalls: "Any",
      hasIntl: "Has Int'l Calls",
      hasSocial: "Has Social Data",
      unlimitedSocial: "Unlimited Social",
    },
    detail: {
      backToPlans: "Back to Plans",
      back: "Back",
      getThisPlan: "Get This Plan",
      addToCompare: "Add to Compare",
      disclaimer: "You'll be redirected to the carrier's official website to complete your purchase. Simba does not sell SIMs or process payments.",
      planDetails: "Plan Details",
      data: "Data",
      localCalls: "Local Calls",
      sms: "SMS",
      socialMedia: "Social Media",
      intlCalls: "International Calls",
      contract: "Contract / Validity",
      features: "Special Features",
      roaming: "Roaming Data",
      unlimited: "Unlimited",
      mins: "min",
      similarPlans: "Similar Plans",
      visitCarrier: "Visit {carrier}",
      notFound: "Plan not found",
      notFoundDesc: "The plan you're looking for doesn't exist.",
    },
    finder: {
      introTitle: "Smart Plan Finder",
      introDesc: "Answer 5 quick questions and we'll pick the top 3 plans that match your needs.",
      introBullet1: "5 simple yes-or-no questions",
      introBullet2: "Takes less than 30 seconds",
      introBullet3: "150+ plans analyzed for you",
      introStart: "Let's Go",
      introSkip: "Or browse all plans",
      step: "Question",
      back: "Back",
      findMyPlans: "Find My Plans",
      startOver: "Start Over",
      thinking: "Finding your perfect plans...",
      thinkingDesc: "Analyzing 150+ plans to find your best matches",
      resultsTitle: "Your Top 3 Picks",
      resultsSubtitle: "Handpicked from 150+ plans just for you",
      allNoTitle: "Living the simple life, huh?",
      allNoDesc: "You said no to everything — honestly, we respect that. But just in case you still need a SIM card, here are the cheapest plans we could find.",
      allNoJustInCase: "The cheapest plans within your budget — just in case",
      noResults: "No matches found",
      noResultsDesc: "Try different answers or browse all plans manually.",
      notRight: "Not what you're looking for? Browse all plans",
      labelBest: "Best Pick",
      labelRunner: "Runner Up",
      labelValue: "Great Value",
      qInternet: "Do you use the internet?",
      qInternetSub: "Browsing, YouTube, Netflix, apps — anything online",
      qLocalCalls: "Do you make local calls?",
      qLocalCallsSub: "Calling people inside Saudi Arabia",
      qIntlCalls: "Do you call internationally?",
      qIntlCallsSub: "Calling people outside Saudi Arabia",
      qSocial: "Do you use social media?",
      qSocialSub: "WhatsApp, TikTok, Instagram, Snapchat, X",
      qBudget: "What's your monthly budget?",
      qBudgetSub: "Drag the slider or pick a shortcut",
      sar: "SAR",
      ansYes: "Yes",
      ansSometimes: "Sometimes",
      ansNo: "No",
      blurTitle: "Sign up to see the best plans for you",
      blurDesc: "Create a free account to see the best plans for you.",
      blurCta: "Sign Up — It's Free",
    },
    compare: {
      title: "Compare",
      viewPlan: "View Plan",
      perMonth: "/mo",
    },
    home: {
      weCompare: "We compare",
      popularNow: "Popular right now",
      just30Seconds: "Just 30 seconds",
    },
    finderModal: {
      title: "Not sure what you need?",
      desc: "Our Smart Advisor picks the best plan for you in just 30 seconds",
      dismiss: "No thanks, I'll browse",
    },
    common: {
      close: "Close",
    },
    help: {
      title: "Help Center",
      subtitle: "Find answers to common questions or reach out to our team",
      searchPlaceholder: "Search for help...",
      noResults: "No results found",
      noResultsDesc: "Try a different search term",
      contactTitle: "Still need help?",
      chatTitle: "Live Chat",
      chatDesc: "Chat with our AI bot 24/7",
      emailTitle: "Email Us",
      phoneTitle: "Call Us",
      phoneDesc: "Sun-Thu, 9AM-6PM",
      cat_all: "All",
      cat_general: "General",
      cat_plans: "Plans",
      cat_features: "Features",
    },
    profile: {
      title: "Welcome to Simba",
      subtitle: "Sign in to save favorites and get personalized recommendations",
      signIn: "Sign In",
      signUp: "Sign Up",
      name: "Full Name",
      namePlaceholder: "Enter your name",
      phone: "Phone Number",
      phonePlaceholder: "05XXXXXXXX",
      password: "Password",
      passwordPlaceholder: "Enter your password",
      signInBtn: "Sign In",
      signUpBtn: "Create Account",
      forgot: "Forgot password?",
      demoNotice: "This is a demo. No data is stored or processed.",
      whyJoin: "Why create an account?",
      feat1Title: "Save Favorites",
      feat1Desc: "Bookmark plans you like and compare them later",
      feat2Title: "Price Alerts",
      feat2Desc: "Get notified when plans drop in price",
      feat3Title: "Secure & Private",
      feat3Desc: "Your data is never shared with carriers",
      welcome: "Welcome back",
      logout: "Sign Out",
      chatDesc: "Meet new people and make friends",
      googleSignIn: "Sign in with Google",
      or: "or",
      almostDone: "Almost done!",
      phonePrompt: "Please enter your phone number to complete your profile",
      savePhone: "Save & Continue",
    },
    about: {
      title: "About Simba",
      subtitle: "We're on a mission to make telecom simple, transparent, and fair for everyone in Saudi Arabia.",
      missionTitle: "Our Mission",
      missionDesc: "Saudi Arabia has 8 licensed telecom carriers offering 150+ plans. Finding the right plan shouldn't require visiting 8 different websites, reading fine print, and doing math. Simba exists to solve this — we aggregate every plan, score them objectively, and help you find your perfect match in seconds. We're 100% free, independent, and we never sell SIMs.",
      visionTitle: "Our Vision",
      visionDesc: "We envision a Saudi Arabia where choosing a telecom plan is as easy as picking your favorite coffee order. No confusing jargon, no hidden fees, no regret. Just a simple, honest answer to a simple question: which plan is right for me? We're building toward a future where every person in the Kingdom has the confidence to pick the perfect plan in seconds — and never overpays again.",
      valuesTitle: "Our Values",
      valuesDesc: "We believe independence comes first — we're not affiliated with any carrier, so our recommendations are always 100% unbiased. Transparency is at our core, meaning every price, every feature, and every detail is clearly displayed with no hidden catches. We're obsessed with simplicity, turning complex telecom jargon into language anyone can understand. And above all, we put the user first — every feature we build starts with one question: does this help you find a better plan?",
      howTitle: "How Simba Works",
      carriersTitle: "Available Carriers",
      ctaTitle: "Ready to find your perfect plan?",
      ctaSubtitle: "Join thousands of Saudis who found better plans with Simba",
      statPlans: "Plans compared",
      statCarriers: "Licensed carriers",
      statFree: "Free forever",
    },
    game: {
      title: "Feed Simba",
      subtitle: "Defeat monsters and grow your lion!",
      play: "Play",
      continue: "Continue",
      coins: "SAR",
      perSec: "/s",
      tapHint: "Tap to attack!",
      food: "Food",
      heroes: "Heroes",
      equip: "Equip",
      buy: "Buy",
      upgrade: "Upgrade",
      unlock: "Unlock",
      level: "Lv",
      power: "Power",
      stage: "Stage",
      floor: "Floor",
      highestFloor: "Highest Floor",
      newJourney: "New Journey",
      newJourneyDesc: "Reset progress to earn Prestige Gems for permanent perks",
      newJourneyBtn: "Start New Journey",
      cancel: "Cancel",
      stats: "Stats",
      totalCoins: "Total Earned",
      totalTaps: "Total Taps",
      journeys: "Journeys",
      tapDamage: "Tap Damage",
      multiplier: "Multiplier",
      backToMenu: "Back",
      offlineEarnings: "Welcome back! You earned",
      whileAway: "while away",
      collect: "Collect",
      hp: "HP",
      boss: "Boss",
      bigBoss: "BIG BOSS",
      bossKills: "Bosses Defeated",
      dps: "DPS",
      foodMilk: "Milk",
      foodFish: "Fish",
      foodMeat: "Meat",
      foodFruit: "Fruit",
      foodFeast: "Feast",
      foodRoyal: "Royal Feast",
      simbaKitten: "Kitten",
      simbaCub: "Cub",
      simbaYoungLion: "Young Lion",
      simbaKingLion: "King Lion",
      perks: "Perks",
      gems: "Gems",
      gemsEarned: "gems earned",
      equipItem: "Equip",
      collectItem: "Bag",
      replaces: "Replaces",
      noItems: "Defeat bosses to get chest drops!",
      noItemsSlot: "No items for this slot yet",
      showAll: "Show All",
      equipped: "Equipped",
      emptySlot: "Empty",
      maxLevel: "MAX",
      tapPower: "Tap Power",
      dpsBoost: "DPS Boost",
      critChance: "Crit Master",
      coinBonus: "Gold Rush",
      luckyDrops: "Lucky Drops",
      headStart: "Head Start",
      bossGold: "Boss Bounty",
      chestLuck: "Chest Luck",
      doubleStrike: "Double Strike",
      bossSlayer: "Boss Slayer",
      fuseBoost: "Forge Master",
      tapFrenzy: "Tap Frenzy",
      abilities: "Skills",
      powerStrike: "Power Strike",
      goldRush: "Gold Rush",
      autoTap: "Auto Tap",
      ready: "Ready",
      active: "Active",
      achievements: "Feats",
      achFirstBlood: "First Blood",
      achBossHunter: "Boss Hunter",
      achBossSlayer: "Boss Slayer",
      achFloor10: "Floor 10",
      achFloor25: "Floor 25",
      achFloor50: "Floor 50",
      achFloor100: "Floor 100",
      achGearedUp: "Geared Up",
      achFullyEquipped: "Fully Equipped",
      achNewBeginning: "New Beginning",
      achVeteran: "Veteran",
      achTapMaster: "Tap Master",
      achFloor200: "Floor 200",
      achRichKing: "Rich King",
      achCollector: "Collector",
      achTapLegend: "Tap Legend",
      achReward: "Reward",
      achClaimed: "Claimed",
      achClaim: "Claim",
      dailyReward: "Daily Reward",
      dailyStreak: "Day",
      dailyClaim: "Claim!",
      dailyClaimed: "Come back tomorrow!",
      fusion: "Fuse",
      fusionDesc: "Merge 3 same-rarity items",
      fusionBtn: "Fuse 3 items",
      fusionResult: "New item!",
      runSummary: "Journey Summary",
      runFloor: "Floor reached",
      runBosses: "Bosses killed",
      runCoins: "Coins earned",
      runGems: "Gems to earn",
      confirm: "Confirm",
      tutTap: "Tap the boss to attack!",
      tutFood: "Buy food to power up!",
      tutHeroes: "Hire heroes for auto damage!",
      wallBoss: "WALL BOSS",
      traitRegen: "Regen",
      traitArmor: "Armor",
      traitDodge: "Dodge",
      traitEnrage: "Enrage",
      traitTough: "Tough",
      traitSlow: "Slow",
      traitShield: "Shield",
      dodged: "DODGE!",
      shielded: "SHIELD!",
      companion_eagle: "Eagle",
      companion_wolf: "Wolf",
      companion_panther: "Panther",
      companion_phoenix: "Phoenix",
      companion_tiger: "Tiger",
      companion_dragon: "Dragon",
      companion_griffin: "Griffin",
      companion_thunderbird: "Thunderbird",
      leaderboard: "Leaderboard",
      lbSave: "Save",
      lbEmpty: "No scores yet. Be the first!",
      rolling: "Opening...",
      openChest: "OPEN CHEST!",
      chestProgress: "Chest",
      luckyHit: "LUCKY!",
      prestige: "Prestige",
      prestigeLocked: "Reach Floor 30 to unlock",
      prestigeUnlocked: "New Journey Available!",
      prestigeDesc: "Reset and earn gems for permanent power",
    },
    speedTest: {
      title: "Speed Test",
      subtitle: "Test your internet speed",
      startTest: "Start Test",
      testAgain: "Test Again",
      testing: "Testing...",
      selectCarrier: "Select your carrier",
      download: "Download",
      ping: "Ping",
      jitter: "Jitter",
      mbps: "Mbps",
      ms: "ms",
      idle: "Tap Start to begin",
      runningPing: "Measuring ping...",
      runningDownload: "Measuring download speed...",
      complete: "Test complete",
      error: "Test failed. Check your connection.",
      offline: "You appear to be offline",
      history: "Test History",
      clearHistory: "Clear History",
      noHistory: "No tests yet",
      good: "Good",
      average: "Average",
      poor: "Poor",
    },
    meetChat: {
      title: "Meet People",
      subtitle: "Talk to new people, make real friendships, and have fun conversations — all within the Simba community.",
      feat1: "Get matched with someone new instantly",
      feat2: "Accept or skip — you choose who to talk to",
      feat3: "Your identity stays private",
      startBtn: "Start Meeting People",
      disclaimer: "This is a demo. Messages are simulated.",
      searching: "Finding someone new...",
      searchingDesc: "Matching you with a new person to talk to",
      foundMatch: "We found someone for you!",
      matchSub: "Wants to make new friends",
      accept: "Say Hi",
      skip: "Skip",
      next: "Next",
      endChat: "End",
      stranger: "New Friend",
      online: "Online",
      connected: "Say hi to your new match!",
      placeholder: "Say something...",
      loginRequired: "Join to meet people",
      loginDesc: "Create a free account to start talking to new people and making friends on Simba.",
      signUp: "Create Account",
      signIn: "Sign In",
      report: "Report",
      reportTitle: "Report this person?",
      reportDesc: "They will be reported and you'll be matched with someone new.",
      reportConfirm: "Report & Skip",
      cancel: "Cancel",
      reportSent: "Reported. Finding someone new...",
    },
    pageTitles: { home: "Home", plans: "Browse Plans", planDetail: "Plan Details", finder: "Plan Finder", profile: "Profile", about: "About" },
    interactions: {
      like: "Like",
      dislike: "Dislike",
      comments: "Comments",
      addComment: "Add Comment",
      commentPlaceholder: "Write a comment...",
      signInToInteract: "Sign in to like, dislike, or comment",
      deleteComment: "Delete",
      noComments: "No comments yet. Be the first!",
      justNow: "Just now",
      minutesAgo: "{n}m ago",
      hoursAgo: "{n}h ago",
      daysAgo: "{n}d ago",
      send: "Send",
    },
    types: { Prepaid: "Prepaid", Postpaid: "Postpaid", "Data-only": "Data-only" },
  },
  ar: {
    nav: { home: "الرئيسية", plans: "الباقات", finder: "المستشار", help: "المساعدة", speedTest: "فحص السرعة", profile: "حسابي", signIn: "دخول", game: "لعبة", chat: "تعرّف" },
    hero: {
      headline: "اختار باقتك المثالية بثواني",
      subheadline: "قارن 150+ باقة من كل شركات الاتصالات بالسعودية.",
      ctaFinder: "رشّح لي باقة",
      ctaBrowse: "تصفح كل الباقات",
      trust: "8 شركات • 150+ باقة",
    },
    howItWorks: {
      title: "كيف يشتغل سيمبا؟",
      step1Title: "حدد إحتياجاتك",
      step1Desc: "جاوب على ٥ أسئلة سريعة عن استخدامك وميزانيتك.",
      step2Title: "عرض الخيارات المناسبة",
      step2Desc: "المستشار الذكي يقترح الباقة الأنسب لك.",
      step3Title: "إتمام الشراء",
      step3Desc: "يتم تحويلك إلى الموقع الرسمي لإتمام العملية.",
    },
    finderCta: {
      title: "مو متأكد وش تحتاج؟",
      subtitle: "المستشار الذكي يلقالك الباقة المثالية بـ 30 ثانية",
      cta: "ابدأ المستشار الذكي",
    },
    trending: { title: "الباقات الأكثر طلب", seeAll: "شوف كل الباقات" },
    deals: { title: "العروض الحالية", seeAll: "شوف كل العروض" },
    carriers: { title: "نقارن باقات كل شركات الاتصالات المرخصة" },
    whySimba: {
      title: "ليش سيمبا؟",
      card1Title: "ما نبيع شرائح",
      card1Desc: "نحوّلك لموقع الشركة الرسمي. بدون مخاطر وبدون وسطاء.",
      card2Title: "توصيات محايدة",
      card2Desc: "ما نتبع لأي شركة اتصالات. توصياتنا محايدة 100%.",
      card3Title: "مطابقة ذكية",
      card3Desc: "مستشارنا يحلل احتياجاتك ويلقالك الباقة المثالية من 150+ خيار.",
      card4Title: "دعم حقيقي — دايم",
      card4Desc: "شات ذكي 24/7، وكلاء مباشرين، واتساب، وهاتف. دايم موجودين.",
    },
    stats: {
      plans: "باقة",
      carriers: "شركات",
      free: "مجاني",
      support: "دعم",
      freeLabel: "100%",
      supportLabel: "24/7",
    },
    footer: {
      tagline: "اختار باقتك المثالية بثواني",
      disclaimer: "سيمبا منصة مقارنة مستقلة. ما تتبع لأي شركة اتصالات. كل العلامات التجارية ملك لأصحابها.",
      madeWith: "صُنع بحب ❤ في السعودية",
      quickLinks: "روابط سريعة",
      company: "الشركة",
      aboutUs: "نبذة عن سيمبا",
    },
    planCard: {
      viewDetails: "شوف التفاصيل",
      compare: "قارن",
      selected: "مختار",
      perMonth: "/شهر",
      sar: "SAR",
      data: "بيانات",
      mins: "دقائق",
      sms: "رسائل",
      unlimitedSocial: "تواصل لا محدود",
      social: "تواصل",
    },
    compareBar: {
      selected: "مختارة",
      of: "من",
      selectMore: "اختر باقتين على الأقل",
      selectMoreShort: "اختر المزيد",
      compareNow: "قارن الحين",
      compareAction: "قارن",
      maxToast: "تقدر تقارن 3 باقات بس. شل وحدة عشان تضيف غيرها.",
    },
    chat: {
      greeting: "هلا! أنا بوت سيمبا. كيف أقدر أساعدك؟",
      placeholder: "اكتب رسالة...",
    },
    browse: {
      title: "تصفح كل الباقات",
      subtitle: "قارن 150+ باقة من كل شركات الاتصالات",
      searchPlaceholder: "دوّر على باقة...",
      allCarriers: "كل الشركات",
      allTypes: "كل الأنواع",
      sortBy: "رتّب حسب",
      sortBestValue: "الأفضل قيمة",
      sortPriceLow: "السعر: الأقل أول",
      sortPriceHigh: "السعر: الأعلى أول",
      sortDataHigh: "البيانات: الأكثر أول",
      sortDataLow: "البيانات: الأقل أول",
      sortCallsHigh: "المكالمات: الأكثر أول",
      sortProvider: "الشركة: أ-ي",
      sortName: "الاسم: أ-ي",
      sortNewest: "الأحدث أول",
      showing: "يعرض",
      plans: "باقة",
      of: "من",
      noResults: "ما لقينا باقات تطابق بحثك",
      noResultsDesc: "جرب تعدّل الفلاتر أو كلمة البحث",
      clearFilters: "امسح كل الفلاتر",
      filters: "الفلاتر",
      priceRange: "نطاق السعر",
      dataRange: "البيانات",
      anyData: "الكل",
      unlimited: "مفتوح",
      localCalls: "المكالمات المحلية",
      intlCalls: "المكالمات الدولية",
      socialMedia: "بيانات السوشل ميديا",
      anyCalls: "الكل",
      hasIntl: "فيه مكالمات دولية",
      hasSocial: "فيه بيانات سوشل",
      unlimitedSocial: "سوشل مفتوح",
    },
    detail: {
      backToPlans: "رجوع للباقات",
      back: "رجوع",
      getThisPlan: "خذ الباقة",
      addToCompare: "أضف للمقارنة",
      disclaimer: "بنحولك لموقع الشركة الرسمي عشان تكمل الشراء. سيمبا ما تبيع شرائح ولا تعالج مدفوعات.",
      planDetails: "تفاصيل الباقة",
      data: "البيانات",
      localCalls: "المكالمات المحلية",
      sms: "الرسائل",
      socialMedia: "السوشل ميديا",
      intlCalls: "المكالمات الدولية",
      contract: "العقد / الصلاحية",
      features: "المميزات الخاصة",
      roaming: "بيانات التجوال",
      unlimited: "مفتوح",
      mins: "دقيقة",
      similarPlans: "باقات تشبهها",
      visitCarrier: "روح لـ {carrier}",
      notFound: "الباقة مو موجودة",
      notFoundDesc: "الباقة اللي تدور عليها مو متوفرة.",
    },
    finder: {
      introTitle: "مستشار الباقات الذكي",
      introDesc: "جاوب على 5 أسئلة سريعة وبنختار لك أفضل 3 باقات تناسبك. بدون تعقيد.",
      introBullet1: "5 أسئلة بسيطة بنعم أو لا",
      introBullet2: "ما تاخذ أكثر من 30 ثانية",
      introBullet3: "نحلل 150+ باقة لك",
      introStart: "يلا نبدأ",
      introSkip: "أو تصفح كل الباقات",
      step: "سؤال",
      back: "رجوع",
      findMyPlans: "أعرض باقاتي",
      startOver: "ابدأ من جديد",
      thinking: "ندوّر لك على أفضل الباقات...",
      thinkingDesc: "نحلل 150+ باقة عشان نلقاك الأنسب",
      resultsTitle: "أفضل 3 باقات لك",
      resultsSubtitle: "اخترناها لك من بين 150+ باقة",
      allNoTitle: "تبي تعيش حياة بسيطة؟",
      allNoDesc: "قلت لا على كل شي — نحترم كذا بصراحة. بس إذا تحتاج شريحة على الأقل، هذي أرخص الباقات اللي لقيناها لك.",
      allNoJustInCase: "أرخص الباقات ضمن ميزانيتك — على الاحتياط",
      noResults: "ما لقينا باقات مطابقة",
      noResultsDesc: "جرب إجابات ثانية أو تصفح كل الباقات.",
      notRight: "مو اللي تدور عليه؟ تصفح كل الباقات",
      labelBest: "الاختيار الأفضل",
      labelRunner: "الوصيف",
      labelValue: "أفضل قيمة",
      qInternet: "تستخدم النت؟",
      qInternetSub: "تصفح، يوتيوب، نتفلكس، تطبيقات — أي شي أونلاين",
      qLocalCalls: "تتصل محلي؟",
      qLocalCallsSub: "مكالمات لأرقام داخل السعودية",
      qIntlCalls: "تتصل دولي؟",
      qIntlCallsSub: "مكالمات لأرقام برا السعودية",
      qSocial: "تستخدم السوشل ميديا؟",
      qSocialSub: "واتساب، تيك توك، انستقرام، سناب، اكس",
      qBudget: "كم ميزانيتك الشهرية؟",
      qBudgetSub: "حرّك السلايدر أو اختر مبلغ",
      sar: "ريال",
      ansYes: "نعم",
      ansSometimes: "أحياناً",
      ansNo: "لا",
      blurTitle: "سجّل عشان تشوف أفضل الباقات لك",
      blurDesc: "سوّ حساب مجاني عشان تشوف أفضل الباقات لك.",
      blurCta: "سجّل — مجاناً",
    },
    compare: {
      title: "مقارنة",
      viewPlan: "التفاصيل",
      perMonth: "/شهر",
    },
    home: {
      weCompare: "نقارن من",
      popularNow: "الأكثر رواجاً",
      just30Seconds: "30 ثانية فقط",
    },
    finderModal: {
      title: "مو متأكد وش تبي؟",
      desc: "المستشار الذكي يختار لك أفضل باقة بـ 30 ثانية بس",
      dismiss: "لا، أبي أتصفح",
    },
    common: {
      close: "إغلاق",
    },
    help: {
      title: "مركز المساعدة",
      subtitle: "اختار إجابات لأسئلتك أو تواصل مع فريقنا",
      searchPlaceholder: "دوّر على إجابة...",
      noResults: "ما لقينا نتائج",
      noResultsDesc: "جرب كلمة بحث ثانية",
      contactTitle: "لسا تحتاج مساعدة؟",
      chatTitle: "محادثة مباشرة",
      chatDesc: "كلّم بوتنا الذكي 24/7",
      emailTitle: "راسلنا",
      phoneTitle: "كلّمنا",
      phoneDesc: "أحد-خميس، 9ص-6م",
      cat_all: "الكل",
      cat_general: "عام",
      cat_plans: "الباقات",
      cat_features: "المميزات",
    },
    profile: {
      title: "أهلاً فيك بسيمبا",
      subtitle: "سجّل دخولك عشان تحفظ المفضلات وتحصل على توصيات تناسبك",
      signIn: "دخول",
      signUp: "حساب جديد",
      name: "الاسم الكامل",
      namePlaceholder: "اكتب اسمك",
      phone: "رقم الجوال",
      phonePlaceholder: "05XXXXXXXX",
      password: "الرقم السري",
      passwordPlaceholder: "اكتب الرقم السري",
      signInBtn: "سجّل دخول",
      signUpBtn: "إنشاء حساب",
      forgot: "نسيت الرقم السري؟",
      demoNotice: "هذا عرض تجريبي. ما نخزن ولا نعالج أي بيانات.",
      whyJoin: "ليش تسوي حساب؟",
      feat1Title: "حفظ المفضلات",
      feat1Desc: "احفظ الباقات اللي تعجبك وقارنها بعدين",
      feat2Title: "تنبيهات الأسعار",
      feat2Desc: "نخبرك لما تنزل أسعار الباقات",
      feat3Title: "آمن وخاص",
      feat3Desc: "بياناتك ما تنشار مع شركات الاتصالات أبداً",
      welcome: "يا مرحبا و مسهلا رجعتلنا",
      logout: "تسجيل خروج",
      chatDesc: "تعرّف على ناس جديدة وكوّن صداقات",
      googleSignIn: "سجّل دخول بقوقل",
      or: "أو",
      almostDone: "تقريباً خلصنا!",
      phonePrompt: "ادخل رقم جوالك عشان نكمّل حسابك",
      savePhone: "حفظ ومتابعة",
    },
    about: {
      title: "نبذة عن سيمبا",
      subtitle: "هدفنا نخلي الاتصالات بسيطة وشفافة وعادلة لكل شخص بالسعودية.",
      missionTitle: "مهمتنا",
      missionDesc: "بالسعودية فيه 8 شركات اتصالات مرخصة تقدم 150+ باقة. ما المفروض تزور 8 مواقع وتقرأ شروط وتحسب عشان تلقى الباقة المناسبة. سيمبا موجودة عشان تحل لك هالمشكلة — نجمع كل باقة، نقيّمها بحيادية، ونساعدك تلقى باقتك المثالية بثواني. مجانية 100%، مستقلة، وما نبيع شرائح.",
      visionTitle: "رؤيتنا",
      visionDesc: "نتخيل سعودية يكون فيها اختيار باقة الاتصالات سهل زي ما تختار قهوتك المفضلة. بدون مصطلحات معقدة، بدون رسوم مخفية، وبدون ندم. بس جواب بسيط وصريح لسؤال بسيط: وش الباقة المناسبة لي؟ نبني مستقبل كل شخص بالمملكة يقدر يختار باقته المثالية بثواني — وما يدفع زيادة أبداً.",
      valuesTitle: "قيمنا",
      valuesDesc: "نؤمن إن الاستقلالية تجي أولاً — ما نتبع لأي شركة اتصالات، فتوصياتنا دايم محايدة 100%. الشفافية عندنا أساس، يعني كل سعر وكل ميزة وكل تفصيلة معروضة بوضوح بدون مفاجآت. مهووسين بالبساطة، نحوّل مصطلحات الاتصالات المعقدة للغة أي شخص يفهمها. وفوق كل شي، المستخدم أولاً — كل ميزة نسويها نسأل نفسنا سؤال واحد: هل هذي تساعدك تلقى باقة أفضل؟",
      howTitle: "طريقة سيمبا",
      carriersTitle: "شركات الاتصالات",
      ctaTitle: "جاهز تلقى باقتك المثالية؟",
      ctaSubtitle: "انضم لآلاف السعوديين اللي لقوا باقات أفضل مع سيمبا",
      statPlans: "باقة للمقارنة",
      statCarriers: "شركات مرخصة",
      statFree: "مجاني للأبد",
    },
    game: {
      title: "أطعم سيمبا",
      subtitle: "اهزم الوحوش وكبّر أسدك!",
      play: "العب",
      continue: "استمر",
      coins: "ريال",
      perSec: "/ث",
      tapHint: "اطق للهجوم!",
      food: "الأكل",
      heroes: "الأبطال",
      equip: "تجهيز",
      buy: "اشتر",
      upgrade: "طوّر",
      unlock: "افتح",
      level: "مس",
      power: "القوة",
      stage: "المرحلة",
      floor: "طابق",
      highestFloor: "أعلى طابق",
      newJourney: "رحلة جديدة",
      newJourneyDesc: "أعد البدء واكسب جواهر لمزايا دائمة",
      newJourneyBtn: "ابدأ رحلة جديدة",
      cancel: "إلغاء",
      stats: "الإحصائيات",
      totalCoins: "مجموع الأرباح",
      totalTaps: "مجموع الطقات",
      journeys: "الرحلات",
      tapDamage: "ضرر الطقة",
      multiplier: "المضاعف",
      backToMenu: "رجوع",
      offlineEarnings: "أهلاً! جمعت لك",
      whileAway: "وأنت بعيد",
      collect: "استلم",
      hp: "HP",
      boss: "وحش",
      bigBoss: "الوحش الكبير",
      bossKills: "الوحوش المهزومة",
      dps: "DPS",
      foodMilk: "حليب",
      foodFish: "سمك",
      foodMeat: "لحم",
      foodFruit: "فواكه",
      foodFeast: "وليمة",
      foodRoyal: "وليمة ملكية",
      simbaKitten: "قطة صغيرة",
      simbaCub: "شبل",
      simbaYoungLion: "أسد صغير",
      simbaKingLion: "ملك الغابة",
      perks: "مزايا",
      gems: "جواهر",
      gemsEarned: "جواهر مكتسبة",
      equipItem: "البس",
      collectItem: "الحقيبة",
      replaces: "يستبدل",
      noItems: "اهزم الوحوش لتحصل على صناديق!",
      noItemsSlot: "لا توجد عناصر لهذه الفئة بعد",
      showAll: "عرض الكل",
      equipped: "مُجهّز",
      emptySlot: "فارغ",
      maxLevel: "حد أقصى",
      tapPower: "قوة الضغط",
      dpsBoost: "تعزيز الضرر",
      critChance: "ضربات حاسمة",
      coinBonus: "حمى الذهب",
      luckyDrops: "حظ سعيد",
      headStart: "بداية متقدمة",
      bossGold: "مكافأة الزعيم",
      chestLuck: "حظ الصناديق",
      doubleStrike: "ضربة مزدوجة",
      bossSlayer: "قاتل الزعماء",
      fuseBoost: "سيد الدمج",
      tapFrenzy: "هيجان الضغط",
      abilities: "المهارات",
      powerStrike: "ضربة قوية",
      goldRush: "حمى الذهب",
      autoTap: "طق تلقائي",
      ready: "جاهز",
      active: "نشط",
      achievements: "الإنجازات",
      achFirstBlood: "أول دم",
      achBossHunter: "صياد الوحوش",
      achBossSlayer: "قاتل الوحوش",
      achFloor10: "طابق ١٠",
      achFloor25: "طابق ٢٥",
      achFloor50: "طابق ٥٠",
      achFloor100: "طابق ١٠٠",
      achGearedUp: "مجهز",
      achFullyEquipped: "مجهز بالكامل",
      achNewBeginning: "بداية جديدة",
      achVeteran: "محترف",
      achTapMaster: "سيد الطق",
      achFloor200: "طابق ٢٠٠",
      achRichKing: "ملك الثروة",
      achCollector: "جامع",
      achTapLegend: "أسطورة الطق",
      achReward: "المكافأة",
      achClaimed: "مُستلم",
      achClaim: "استلم",
      dailyReward: "المكافأة اليومية",
      dailyStreak: "يوم",
      dailyClaim: "استلم!",
      dailyClaimed: "عد غداً!",
      fusion: "دمج",
      fusionDesc: "ادمج ٣ قطع بنفس الندرة",
      fusionBtn: "ادمج ٣ قطع",
      fusionResult: "قطعة جديدة!",
      runSummary: "ملخص الرحلة",
      runFloor: "الطابق",
      runBosses: "وحوش مقتولة",
      runCoins: "عملات مكتسبة",
      runGems: "جواهر ستكسب",
      confirm: "تأكيد",
      tutTap: "اطق الوحش للهجوم!",
      tutFood: "اشتر أكل لتقوى!",
      tutHeroes: "وظف أبطال للضرر التلقائي!",
      wallBoss: "وحش الجدار",
      traitRegen: "تجدد",
      traitArmor: "درع",
      traitDodge: "مراوغة",
      traitEnrage: "غضب",
      traitTough: "صلب",
      traitSlow: "بطء",
      traitShield: "حصن",
      dodged: "مراوغة!",
      shielded: "محصن!",
      companion_eagle: "النسر",
      companion_wolf: "الذئب",
      companion_panther: "الفهد",
      companion_phoenix: "العنقاء",
      companion_tiger: "النمر",
      companion_dragon: "التنين",
      companion_griffin: "الغريفون",
      companion_thunderbird: "طائر الرعد",
      leaderboard: "المتصدرين",
      lbSave: "حفظ",
      lbEmpty: "لا توجد نتائج بعد. كن الأول!",
      rolling: "جاري الفتح...",
      openChest: "!افتح الصندوق",
      chestProgress: "صندوق",
      luckyHit: "!محظوظ",
      prestige: "برستيج",
      prestigeLocked: "أوصل طابق ٣٠ للفتح",
      prestigeUnlocked: "رحلة جديدة متاحة!",
      prestigeDesc: "أعد وابدأ واكسب جواهر لقوة دائمة",
    },
    speedTest: {
      title: "فحص السرعة",
      subtitle: "افحص سرعة الإنترنت عندك",
      startTest: "ابدأ الفحص",
      testAgain: "افحص مرة ثانية",
      testing: "جاري الفحص...",
      selectCarrier: "اختر شركتك",
      download: "التحميل",
      ping: "البنق",
      jitter: "التذبذب",
      mbps: "ميقا/ث",
      ms: "مل/ث",
      idle: "اضغط ابدأ للفحص",
      runningPing: "نقيس البنق...",
      runningDownload: "نقيس سرعة التحميل...",
      complete: "انتهى الفحص",
      error: "فشل الفحص. تأكد من اتصالك.",
      offline: "يبدو إنك مو متصل بالنت",
      history: "سجل الفحوصات",
      clearHistory: "مسح السجل",
      noHistory: "ما فيه فحوصات بعد",
      good: "ممتاز",
      average: "متوسط",
      poor: "ضعيف",
    },
    meetChat: {
      title: "تعرّف على ناس",
      subtitle: "كلّم ناس جديدة، كوّن صداقات حقيقية، واستمتع بمحادثات ممتعة — كلها داخل مجتمع سيمبا.",
      feat1: "توصّل بشخص جديد فوراً",
      feat2: "اقبل أو تخطى — أنت تختار مين تكلم",
      feat3: "هويتك تبقى خاصة",
      startBtn: "ابدأ تعرّف على ناس",
      disclaimer: "هذا عرض تجريبي. الرسائل محاكاة.",
      searching: "ندور لك شخص جديد...",
      searchingDesc: "نوصلك بشخص جديد تكلمه",
      foundMatch: "لقيناك شخص!",
      matchSub: "يبي يتعرف على ناس جديدة",
      accept: "قل هلا",
      skip: "تخطى",
      next: "التالي",
      endChat: "إنهاء",
      stranger: "صديق جديد",
      online: "متصل",
      connected: "قل هلا لصديقك الجديد!",
      placeholder: "قل شي...",
      loginRequired: "انضم وتعرف على ناس",
      loginDesc: "سوّ حساب مجاني عشان تبدأ تكلم ناس جديدة وتكوّن صداقات على سيمبا.",
      signUp: "سوّ حساب",
      signIn: "دخول",
      report: "بلّغ",
      reportTitle: "تبلّغ عن هالشخص؟",
      reportDesc: "بيتم التبليغ عنه وبنوصلك بشخص جديد.",
      reportConfirm: "بلّغ وتخطى",
      cancel: "إلغاء",
      reportSent: "تم البلاغ. ندور لك شخص جديد...",
    },
    pageTitles: { home: "الرئيسية", plans: "تصفح الباقات", planDetail: "تفاصيل الباقة", finder: "المستشار الذكي", profile: "حسابي", about: "نبذة عن سيمبا" },
    interactions: {
      like: "إعجاب",
      dislike: "عدم إعجاب",
      comments: "التعليقات",
      addComment: "أضف تعليق",
      commentPlaceholder: "اكتب تعليق...",
      signInToInteract: "سجّل دخولك عشان تتفاعل أو تعلق",
      deleteComment: "حذف",
      noComments: "ما فيه تعليقات بعد. كن أول معلق!",
      justNow: "الحين",
      minutesAgo: "قبل {n} دقيقة",
      hoursAgo: "قبل {n} ساعة",
      daysAgo: "قبل {n} يوم",
      send: "إرسال",
    },
    types: { Prepaid: "مسبق الدفع", Postpaid: "مفوتر", "Data-only": "بيانات فقط" },
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => (localStorage.getItem('simba-lang') as Lang) || 'en');

  const [theme, setTheme] = useState<Theme>('light');

  const toggleLang = useCallback(() => {
    setLang(prev => {
      const next = prev === 'en' ? 'ar' : 'en';
      localStorage.setItem('simba-lang', next);
      return next;
    });
  }, []);

  const toggleTheme = useCallback(() => {
    setTheme(prev => (prev === 'light' ? 'dark' : 'light'));
  }, []);

  const t = useCallback((path: string, params?: Record<string, string>): string => {
    const keys = path.split('.');
    let result: unknown = translations[lang];
    for (const key of keys) {
      result = (result as Record<string, unknown>)?.[key];
    }
    if (!result) return path;
    if (params && typeof result === 'string') {
      return Object.entries(params).reduce(
        (str, [k, v]) => str.replace(`{${k}}`, v),
        result
      );
    }
    return result as string;
  }, [lang]);

  useEffect(() => {
    const html = document.documentElement;
    html.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');
    html.setAttribute('lang', lang);
  }, [lang]);

  useEffect(() => {
    document.documentElement.classList.toggle('dark', theme === 'dark');
  }, [theme]);

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t, theme, setTheme, toggleTheme }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used within LanguageProvider');
  return ctx;
};
